config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :bands, only: [:show, :index] do
    resources :participants, only: [:show]
    get "/profile" => "bands#profile"
  end

  resources :venues, only: [:index, :show]

  resources :concerts, only: [:index, :show, :create]

  get "/calendar/bands/:id/concerts" => "calendar#band_concerts"
  get "/calendar/venues-availables/:date" => "calendar#venues_availables"
  
  

  

end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :participants
  has_many :concerts

  validates :name, :gender, :bandtype, :city, :language, presence: true

  def generate_photo_url name
    photo_file = name.downcase.strip.gsub(" ","-")
    photo_url = "bands/" + photo_file + ".jpg"
  end

  def list_outstanding_concerts
    concerts.where('date >= ?', Date.today)
  end
end

app/models/concert.rb
class Concert < ActiveRecord::Base
  belongs_to :band
  belongs_to :venue

  validates :band_id, :venue_id, :date, :time, presence: true
  validates :date, uniqueness: { scope: :band_id,
    message: "This band have a concert in this day yet" }
  validates :date, uniqueness: { scope: :venue_id,
    message: "This venue have a concert in this day yet" }

  def self.order_by_date
    order("date ASC")
  end

  def self.next_concerts
    where("date >= ?", Date.today)
  end

  def time_format
    time.strftime("%H:%M")
  end

  def date_next_concerts
    date.strftime("%b %d")
  end

  def venue
    Venue.find_by_id(venue_id)
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :band

  validates :name, :email, :instrument, presence: true

  def generate_photo_url name
    photo_file = name.downcase.strip.gsub(" ","-")
    photo_url = "participants/" + photo_file + ".jpg"
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :concerts
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  validates :name, :email, :address, presence: true

  def generate_photo_url name
    photo_file = name.downcase.strip.gsub(" ","-")
    photo_url = "venues/" + photo_file + ".jpg"
  end

  def self.availables date_to_check
    Venue.where("id NOT IN (SELECT DISTINCT(venue_id) FROM concerts WHERE date = ?)",date_to_check)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def show
    @band = Band.find_by_id(params[:id])
    @concerts = @band.concerts.next_concerts.order_by_date
  end

  def index
    @bands = Band.all
  end

  def add_photo_url
    photo_url = generate_photo_url (name)
  end

  def profile
    @band = Band.find_by_id(params[:band_id])
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController

  def band_concerts
    band = Band.find_by_id(params[:id])
    @band_concerts = band.concerts.sort_by &:date

    if @band_concerts
      render :band_concerts
    else
      render status: 404, json: {error: "Concerts not found"}
    end
  end

  def venues_availables
    date = params[:date]
    @venues_availables = Venue.availables(date)

    if @venues_availables
      render :venues_availables
    else
      render status: 404, json: {error: "No venues"}
    end
  end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

  def show
    @concert = Concert.find_by_id(params[:id])
    @band = Band.find_by_id(@concert.band_id)
    @venue = Venue.find_by_id(@concert.venue_id)
  end

  def index
    @concerts = Concert.all
  end

  def create
    new_concert = Concert.create concert_params
    if new_concert
      render json: new_concert
    end
  end

  private

  def concert_params
    params.require(:concert).permit(:band_id, :venue_id, :date, :time)
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def show
    @participant = Participant.find_by_id(params[:id])
    @band = Band.find_by_id(@participant.band_id)
  end

  private

  def participant_params
    params.require(:participant).permit(:name, :email, :instrument)
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

  def show
    @venue = Venue.find_by_id(params[:id])
  end

  def index
    @venues = Venue.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @concerts = Concert.next_concerts.order_by_date
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bands/_band_info.html.erb
<section id="band-info" class="container">
  <div class="col-md-3">
    <div id="profile-image">
      <%= image_tag @band.generate_photo_url(@band.name) %>
    </div>
  </div>
  <div class="col-md-9">
    <%= image_tag "quaver.png" %>
    <h2>Events</h2>
    <h1 class="profile-band-name" data-id="<%= @band.id %>"><%= @band.name %></h1>
    <p><%= @band.description %></p>
  </div>
</section>

app/views/bands/_next_concerts.html.erb
<h1>Next concerts</h1>
<ul class="list-next-concerts container">

<% @concerts.each do |concert| %>

  <li class="item-next-concerts container">
    <a href="/concerts/<%= concert.id %>">
      <div class="next-concert-quaver">
        <img src="/assets/quaver-little.png" alt="quaver"/>
      </div>
      <div class="next-concert-data fix-data-date">
        <span class="title">Date</span>
        <p class="data"><%= concert.date_next_concerts %></p>
      </div>
      <div class="next-concert-data fix-data-time">
        <span class="title hour">Time</span>
        <p class="data hour"><%= concert.time_format %></p>
      </div>
      <div class="next-concert-data">
        <span class="title">Venue</span>
        <p class="data"><%= concert.venue.name %></p>
      </div>
  <!--     <div class="next-concert-data">
        <span class="title">Address</span>
        <p class="data address"><%= concert.venue.address %></p>
      </div> -->
    </a>
  </li>
  

<% end %>

</ul>

app/views/bands/index.html.erb
<div class="content container">
  <h1>Bands</h1>
  <section class="index-panels">
    <% @bands.each do |band| %>
      <%= render 'partials/panels/panel_band', band: band %>
    <% end %>
  </section>
</div>

app/views/bands/profile.html.erb
<!-- Twitter script -->

<script>
  window.twttr = (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0],
      t = window.twttr || {};
    if (d.getElementById(id)) return t;
    js = d.createElement(s);
    js.id = id;
    js.src = "https://platform.twitter.com/widgets.js";
    fjs.parentNode.insertBefore(js, fjs);
   
    t._e = [];
    t.ready = function(f) {
      t._e.push(f);
    };
   
    return t;
  }(document, "script", "twitter-wjs"));
</script>

<!-- facebook script -->

<!-- <div id="fb-root"></div>
<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_ES/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>
 -->
<!-- end rrss -->

<%= render 'band_info' %>

<section class="calendar band-calendar container-fluid">
    <div id='calendar' class="container"></div>
    <div class="calendar-venues-availables container"></div>  
</section>

<section id="next-concerts" class="container"></section>

app/views/bands/show.html.erb
<section id="show-info" class="container">
  <div class="col-md-4">
    <div id="show-image">
      <%= image_tag @band.generate_photo_url(@band.name) %>
    </div>
  </div>
  <div class="col-md-8">
    <%= image_tag "quaver.png", class: "category-icon", alt: "quaver-icon" %>
    <h2 class="show-category">Band</h2>
    <h1 class="profile-band-name" data-id="<%= @band.id %>">
      <%= @band.name %>
    </h1>
    <p><%= @band.description %></p>

    <div id="show-properties">   
      <div class="show-data">
        <p class="title">gender:</p>
        <p><%= @band.gender %></p>
      </div>
      <div class="show-data">
        <p class="title">band type:</p>
        <p><%= @band.bandtype %></p>
      </div>
      <div class="show-data">
        <p class="title">city:</p>
        <p><%= @band.city %></p>
      </div>
      <div class="show-data">
        <p class="title">language:</p>
        <p><%= @band.language %></p>
      </div>
    </div>

    <div class="band-participants">
      <p class="title">participants:</p>
      <ul id="band-list-participants">
        <% @band.participants.each do |participant| %>
           <li class="item-band-list-participants">
             <div class="participant-img">
               <%= image_tag participant.generate_photo_url(participant.name) %>
             </div>
             <div class="participant-data">
               <%= link_to participant.name, band_participant_path(participant.band_id, participant.id), class: "participant-name" %>
               <p class="participant-instrument"><%= participant.instrument %></p>
             </div>
           </li>   
        <% end %>    
      </ul>
    </div>

    <%= link_to "Profile", band_profile_path(@band), class: "btn btn-green btn-profile"%>

  </div>
</section>

<% if @band.list_outstanding_concerts.length > 0 %>
  <section id="next-concerts" class="container-fluid bkg-next-concerts">
    <div class="container">
      <%= render "next_concerts" %>
    </div>
  </section>
<% end %>

app/views/concerts/index.html.erb
<div class="content container">
  <h1>Concerts</h1>
  <section class="index-panels">
    <% @concerts.each do |concert| %>
      <%= render 'partials/panels/panel_concert', 
                 concert: concert, 
                 band: Band.find_by_id(concert.band_id),
                 venue: Venue.find_by_id(concert.venue_id)%>
    <% end %>
  </section>
</div>

app/views/concerts/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>

<section id="show-info" class="container">
  <div class="col-md-4">
    <div id="show-image">
      <%= image_tag @band.generate_photo_url(@band.name) %>
    </div>
  </div>
  <div class="show-content col-md-8">
    <%= image_tag "thunder-icon.png", class: "category-icon", alt: "thunder-icon" %>
    <h2 class="show-category">Concert</h2>
    <h1 class="concerts-band-name">
      <%= link_to @band.name, band_path(@band) %>
    </h1>
    <h3>
      Gender <%= @band.gender %> (<%= @band.bandtype %> music)
    </h3>
    <p><%= @band.language %></p>
    <h2 class="concerts-venue-name">
      <%= link_to @venue.name, venue_path(@venue) %>
    </h2>
    <div class="show-data">
      <p class="title">date:</p>
      <p><%= @concert.date %></p>
    </div>
    <div class="show-data">
      <p class="title">hour:</p>
      <p><%= @concert.time_format %></p>
    </div>
    <div class="show-data">
      <p class="title">address:</p>
      <p id="venue-address" data-latitude="<%= @venue.latitude %>" data-longitude="<%= @venue.longitude %>"><%= @venue.address %></p>   
    </div>
    <div id="map"></div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>BandLive</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>


</head>
  <body>
    <header>
      <%= render "partials/navbar" %>
    </header>

      <%= yield %>

    <%= render "partials/footer" %>
  </body>
</html>

app/views/login/show.html.erb
login

app/views/partials/_footer.html.erb
<footer id="page-footer" class="footer-bckg footer-size">
  <div class="container">
    <div class="logo-footer">
      <a href="<%= root_path %>">
        <%= image_tag 'logo-bandlive.png' %>
      </a>          
    </div>
    <div class="copyright">
      <span>©December 2015</span>
    </div>
    <div class="navbar-default navbar-right footer-bckg footer-list-margin-top">
      <ul id="footer-list" class="nav navbar-nav">
        <li><a href="#fakelink">About</a></li>
        <li><a href="<%= bands_path %>">Bands</a></li>
        <li><a href="<%= venues_path %>">Venues</a></li>
        <li><a href="<%= concerts_path %>">Concerts</a></li>
        <li><a href="#fakelink">Contact</a></li>
      </ul>
    </div>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default grad-navbar div-with-shadow">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">  
      <div class="navbar-header">
      
        <h1 class="logo">
          <a href="<%= root_path %>">
            <%= image_tag 'logo-bandlive.png' %>
          </a>
        </h1>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-right main-menu" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="<%= bands_path %>">Bands</a></li>
          <li><a href="<%= venues_path %>">Venues</a></li>
          <li><a href="<%= concerts_path %>">Concerts</a></li>
        </ul>
        <%= link_to "Login", "#fakelink", class: "btn btn-default" %>
      </div>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/panels/_panel_band.html.erb
<div class="col-md-3 col-sm-6">
  <a href="<%= band_path(band) %>" id="panel-link">
    <article class="panel">
      <div class="panel-image">
        <%= image_tag band.generate_photo_url(band.name) %>
      </div>
      <header>
        <h1><%= band.name %></h1>
      </header>
      <div class="panel-content">
        <p>Gender <%= band.gender %>-<%= band.bandtype %> music</p>
        <p>Language - <%= band.language %></p>
      </div>
    </article>
  </a>
</div>

app/views/partials/panels/_panel_concert.html.erb
<div class="col-md-3 col-sm-6">
  <a href="<%= concert_path(concert) %>" id="panel-link">
    <article class="panel">
      <div class="panel-image">
        <%= image_tag band.generate_photo_url(band.name) %>
      </div>
      <footer>
        <p><span class="panel-date"><%= concert.date.day %> <%= concert.date.strftime("%b") %></span> at <%= venue.name %></p>
      </footer>
      <header>
        <h1><%= band.name %></h1>
      </header>
      <div class="panel-content">
        <p>Gender <%= band.gender %>-<%= band.bandtype %> music</p>
        <p>Language - <%= band.language %></p>
      </div>
      <div class="social-share">
        <%= link_to "share" , "#fakelink" ,class: "btn btn-green"%>
      </div>
    </article>
  </a>
</div>

app/views/partials/panels/_panel_venue.html.erb
<div class="col-md-3 col-sm-6">
  <a href="<%= venue_path(venue) %>" id="panel-link">
    <article class="panel">
      <header>
        <h1><%= venue.name %></h1>
      </header>
      <div class="panel-image">
        <%= image_tag venue.generate_photo_url(venue.name) %>
      </div>
      <div class="panel-content">
        <p>email: <%= venue.email %></p>
        <p>address: <%= venue.address %></p>        
      </div>
    </article>
  </a>
</div>

app/views/participants/show.html.erb
<section id="show-info" class="container">
  <div class="col-md-4">
    <div id="show-image">
      <%= image_tag @participant.generate_photo_url(@participant.name) %>
    </div>
  </div>
  <div class="show-content col-md-8">
    <h1 class="participant-name">
      <%= @participant.name %>
    </h1>
    <div id="show-properties">   
      <div class="show-data">
        <p class="title">email:</p>
        <p><%= @participant.email %></p>
      </div>
    </div>
    <div id="show-properties">   
      <div class="show-data">
        <p class="title">instrument:
        <p><%= @participant.instrument %></p>
      </div>
    </div>
    <div id="show-properties">   
      <div class="show-data">
        <p class="title">band:</p>
        <p><%= link_to @band.name, band_path(@band.id) %></p>
      </div>
    </div>
  </div>
</section>

app/views/venues/index.html.erb
<div class="content container">
  <h1>Venues</h1>
  <section class="index-panels">
    <% @venues.each do |venue| %>
      <%= render 'partials/panels/panel_venue', venue: venue %>
    <% end %>
  </section>
</div>

app/views/venues/show.html.erb
<script src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>

<section id="show-info" class="container">
  <div class="col-md-3">
    <div id="show-image">
      <%= image_tag @venue.generate_photo_url(@venue.name) %>
    </div>
  </div>
  <div class="show-content col-md-9">
    <%= image_tag "quaver.png", class: "category-icon", alt: "quaver" %>
    <h2 class="show-category">Venue</h2>
    <h1 class="venues-name">
      <%= @venue.name %>
    </h1>
    <p><%= @venue.description %></p>
    <div id="show-properties">
      <div class="show-data">
        <p class="title">email: </p>
        <p id="venue-email"><%= @venue.email %></p>
      </div>
      <div class="show-data">
        <p class="title">address: </p> 
        <p id="venue-address" data-latitude="<%= @venue.latitude %>" data-longitude="<%= @venue.longitude %>"><%= @venue.address %></p>
      </div>
    </div> 
    <div id="map"></div>
  </div>
</section>

<!--   <section class="container col-md-12 next-concerts">
    <h1>Next Concerts</h1>
  </section> -->

app/views/welcome/index.html.erb
<section class="main-banner container-fluid div-with-shadow">
  <div class="main-banner-image col-md-4 main-banner-left">
    <%= image_tag("main-banner.png", alt: "guitarrist") %>
  </div>
  <div class="col-md-8 main-banner-right">
    <div class="main-banner-title">
      <h1>Plan a concert!</h1>
    </div>
    <div class="main-banner-content">
      <h3>Do you want to play?  It’s so simple, just select a date and apply to play at the venue.</h3>
    </div>
    <div class="main-banner-form">
      <%= form_tag("/search", method: "get") do %>
        <%= label_tag(:date, "Date", class: "input-label") %><br/>
        <%= date_field_tag(:date, Date.today, class: "input-white") %>
        <%= text_field_tag(:location, nil, class: "input-white") %>
        <%= link_to "Show me venues", "#fakelink", class: "btn btn-green" %>
        <!-- <#%= submit_tag("Show me venues", class: "btn btn-green") %> -->
      <% end %>
    </div>
  </div>
</section>

<div class="content container">
  <section class="index-panels">
    <h1>Concerts</h1>

    <% @concerts.each do |concert| %>
      <%= render 'partials/panels/panel_concert', 
                 concert: concert, 
                 band: Band.find_by_id(concert.band_id),
                 venue: Venue.find_by_id(concert.venue_id)%>
    <% end %>
   
  </section>
</div>